### ISSUE TITLE
Customize the score to win

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#30]
When user clicks on settings it should display a 3 radio buttons to give the user the ability to customize the score points.

3 main options:
- 5 points
- 10 points
- 15 points

When user customize the score we should customize the winningNumber state:

It should be set in both modes "single" and "two players"
 
![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/91aa2de7-ae86-4fd6-9efe-33e569554e5a)

**Comment by aditya4196** [comment]
@Ramzi-Abidi Actually since i worked on the Settings tab (Issue 43)
I had completed this issue too as this is connected to Issue 43. Can you assign me so then i can generate the PR. 
I can even get Issue no 45 (game theme) and generate a PR for Issue no 30 and Issue no 45 together
I even have a small simple components diagram

**Comment by Ramzi-Abidi** [comment]
> @Ramzi-Abidi Actually since i worked on the Settings tab (Issue 43) I had completed this issue too as this is connected to Issue 43. Can you assign me so then i can generate the PR. I can even get Issue no 45 (game theme) and generate a PR for Issue no 30 and Issue no 45 together I even have a small simple components diagram

I will assign you this issue, try please to address each issue separately to facilitate easier review of pull requests!

**Comment by Ramzi-Abidi** [comment]
@aditya4196  It's fantastic that you're an active contributor! Please focus on resolving this issue first and submit a PR. Then, comment under any other issue you'd like to work on, and I'll assign it to you. Thank you!
